### ISSUE TITLE
使用 audioOverride 时主服务器程序出现错误

### ISSUE THREAD

**Issue by shacha086** [Misaka12456/ArcaeaServer2#8]
Traceback: 
![{1L)5C4X0P7YVWR2U7)2 0X](https://user-images.githubusercontent.com/50512232/163547860-07962968-d02d-4c56-8b73-f396aa0e2673.png)

Songlist info: 
![image](https://user-images.githubusercontent.com/50512232/163548001-5748655a-e08a-4bcf-918b-069411970126.png)

File info: 
![image](https://user-images.githubusercontent.com/50512232/163548055-f40cda54-8a70-43ee-92e4-5cade2cbd33a.png)

**Comment by Misaka12456** [comment]
这个其实不是下载服务器的bug 这个是主服务器(Team123it.Arcaea.MarveCube)的（
感谢反馈 我会尽快修复

**Comment by shacha086** [comment]
> 这个其实不是下载服务器的bug 这个是主服务器(Team123it.Arcaea.MarveCube)的（ 感谢反馈 我会尽快修复

收到（

**Comment by Misaka12456** [comment]
我还没更新呢你close干啥（
